# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site settings
title: "James Muiruri Mutiria"
subtitle: "IT Support | Network Engineering | Cybersecurity Enthusiast"
description: "Portfolio showcasing my IT journey — from hardware support to offensive and defensive cybersecurity."
url: "https://your-username.github.io" # Change to your GitHub Pages URL or custom domain
baseurl: "" # Leave empty unless your site is in a subdirectory

# Author settings
author:
  name: "James Muiruri Mutiria"
  avatar: "/assets/images/avatar.png" # Add your photo here later
  bio: >
    IT enthusiast passionate about cybersecurity, networking, and IT support. Always learning, always growing.
  location: "Kenya"
  email: "jamesmuiruri820@gmail.com"     # <--- Add your email here
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/james-muiruri-325b23258"   # <--- Add LinkedIn URL here
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/James-Muiruri"   # optional
    - label: "Phone"
      icon: "fas fa-phone"
      url: "tel:+254704070009"   # <--- Add phone number here (international format)

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Theme settings
minimal_mistakes_skin: "dark"   # <--- Tech-themed dark look
locale: "en-US"
search: true

# Navigation
header_pages:
  - _pages/about.md
  - _pages/skills.md
  - _pages/projects.md
  - _pages/resume.md
  - _pages/contact.md

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Footer
footer:
  links:
    - label: "Email"
      url: "mailto:your-email@example.com"   # <--- Again, your email here
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/your-linkedin-profile"
    - label: "Phone"
      url: "tel:+254700000000"
